# -*- coding: utf-8 -*-
"""logo_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWuhzf3dvTkJ14G87f-l3s-MsE79eZ89
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe

# ----------------------------
# Monodromy Labs orbit logo
# Inspired by stable orbit fragments / 3-body aesthetics
# ----------------------------

# Colors
BLUE   = "#57BEEA"
GREEN  = "#43B38A"
YELLOW = "#D8B23C"
BG     = "white"

# Canvas / export
FIGSIZE = (6, 6)
LINEWIDTH = 10
OUTLINE = 4   # white halo for clean separation
DPI = 400

def orbit_arc(
    radius=1.0,
    center=(0.0, 0.0),
    sx=1.0,
    sy=1.0,
    rotation_deg=0.0,
    start_deg=20,
    end_deg=320,
    n=500,
    tail_start=0.18,
    tail_end=0.18,
):
    """
    Generate an open arc that looks like an orbit fragment.
    tail_start / tail_end slightly extend the endpoints along the tangent,
    giving the logo its elegant 'flying stroke' feel.
    """
    t = np.linspace(np.deg2rad(start_deg), np.deg2rad(end_deg), n)

    # Slight ellipse instead of perfect circle for a more 'orbital' feel
    x = radius * sx * np.cos(t)
    y = radius * sy * np.sin(t)

    # Rotate
    theta = np.deg2rad(rotation_deg)
    xr = x * np.cos(theta) - y * np.sin(theta)
    yr = x * np.sin(theta) + y * np.cos(theta)

    # Shift to center
    xr = xr + center[0]
    yr = yr + center[1]

    # Extend start/end a little along local tangent
    pts = np.column_stack([xr, yr])

    # start tangent
    p0, p1 = pts[0], pts[1]
    v0 = p0 - p1
    v0 = v0 / np.linalg.norm(v0)
    start_extra = p0 + tail_start * v0

    # end tangent
    pn1, pn = pts[-2], pts[-1]
    vn = pn - pn1
    vn = vn / np.linalg.norm(vn)
    end_extra = pn + tail_end * vn

    pts = np.vstack([start_extra, pts, end_extra])
    return pts

# Three orbit fragments, tuned to resemble the uploaded sketch
blue_arc = orbit_arc(
    radius=1.02,
    center=(-0.02, 0.18),
    sx=1.12,
    sy=0.98,
    rotation_deg=-12,
    start_deg=28,
    end_deg=338,
    tail_start=0.14,
    tail_end=0.14,
)

green_arc = orbit_arc(
    radius=0.98,
    center=(-0.14, -0.06),
    sx=1.00,
    sy=1.03,
    rotation_deg=10,
    start_deg=205,
    end_deg=528,   # wraps more than one turn fragment style
    tail_start=0.12,
    tail_end=0.12,
)

yellow_arc = orbit_arc(
    radius=0.93,
    center=(0.10, -0.12),
    sx=1.06,
    sy=0.97,
    rotation_deg=16,
    start_deg=38,
    end_deg=315,
    tail_start=0.12,
    tail_end=0.12,
)

fig, ax = plt.subplots(figsize=FIGSIZE, facecolor=BG)
ax.set_facecolor(BG)

def draw_orbit(points, color, z):
    ax.plot(
        points[:, 0],
        points[:, 1],
        color=color,
        lw=LINEWIDTH,
        solid_capstyle="round",
        solid_joinstyle="round",
        zorder=z,
        path_effects=[
            pe.Stroke(linewidth=LINEWIDTH + OUTLINE, foreground="white"),
            pe.Normal(),
        ],
    )

# Draw order chosen for a gentle interlacing feel
draw_orbit(green_arc, GREEN, 2)
draw_orbit(yellow_arc, YELLOW, 3)
draw_orbit(blue_arc, BLUE, 4)

# Clean framing
all_pts = np.vstack([blue_arc, green_arc, yellow_arc])
xmin, ymin = all_pts.min(axis=0)
xmax, ymax = all_pts.max(axis=0)

pad = 0.28
ax.set_xlim(xmin - pad, xmax + pad)
ax.set_ylim(ymin - pad, ymax + pad)
ax.set_aspect("equal")
ax.axis("off")

plt.tight_layout(pad=0)
plt.show()

# Save outputs
fig.savefig("monodromy_orbit_logo.svg", bbox_inches="tight", pad_inches=0.02, facecolor=BG)
fig.savefig("monodromy_orbit_logo.png", dpi=DPI, bbox_inches="tight", pad_inches=0.02, facecolor=BG)

print("Saved:")
print(" - monodromy_orbit_logo.svg")
print(" - monodromy_orbit_logo.png")